[package]
name = "lightway-app-utils"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/expressvpn/lightway"
authors = ["lightway-developers@expressvpn.com"]
license = "GPL-2.0-only"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "tokio" ]
tokio = [ "dep:tokio", "dep:tokio-stream" ]
io-uring = [ "dep:io-uring", "dep:async-channel", "dep:tokio", "dep:tokio-eventfd" ]

[dependencies]
lightway-core = { path = "../lightway-core" }
humantime = "2.1.0"
serde = "1.0.189"
serde_with = "3.4.0"
tokio = { version = "1.33.0", features = ["macros", "rt", "sync", "time"], optional = true }
tokio-stream = { version = "0.1.14", optional = true }
clap = { version = "4.4.7", features = ["derive"] }
tracing-subscriber = { version = "0.3.17", features = ["json"] }
tokio-util = "0.7.10"
io-uring = {  version = "0.6.3", optional = true }
async-channel = { version = "2.1.1", optional = true }
tokio-eventfd = { version = "0.2.1", optional = true }
anyhow = "1.0.79"
bytes = "1.5.0"
dashmap = "6.0.1"
thiserror = "1.0.57"
tokio-tun = "0.11.2"
metrics = "0.23.0"

[[example]]
name = "udprelay"
path = "examples/udprelay.rs"

[dev-dependencies]
async-trait = "0.1.77"
pnet = "0.35.0"
tokio-eventfd = "0.2.1"
tokio-tun = "0.11.2"
