[package]
name = "lightway-client"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/expressvpn/lightway"
authors = ["lightway-developers@expressvpn.com"]
license = "GPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["postquantum"]
debug = ["lightway-core/debug"]
postquantum = ["lightway-core/postquantum"]

[dependencies]
lightway-core = { path = "../lightway-core" }
lightway-app-utils = { path = "../lightway-app-utils" }
tokio = { version = "1.31.0", features = ["rt-multi-thread", "macros", "net", "time", "io-util"] }
clap = { version = "4.4.1", features = ["derive"] }
anyhow = "1.0.75"
async-trait = "0.1.73"
bytes = "1.4.0"
serde = { version = "1.0.189", features = ["derive"] }
tokio-tun = "0.11.2"
tracing-subscriber = { version = "0.3.17" }
tracing = "0.1.37"
tokio-stream = { version = "0.1.14", features = ["time"] }
twelf = { version = "0.15.0", default-features = false, features = ["env", "clap", "yaml"]}
socket2 = "0.5.5"
bytesize = { version = "1.3.0", features = ["serde"] }
libc = "0.2.152"
futures = "0.3.30"
tokio-util = "0.7.10"
ctrlc = { version = "3.4.2", features = ["termination"] }
pnet = "0.35.0"
educe = { version = "0.5.11", default-features = false, features = ["Debug"] }

[dev-dependencies]
more-asserts = "0.3.1"
